name: Build Sofle Pro Firmware from layout.json

on:
  push:
    paths:
      - 'keyboards/mechboards/sofle/pro/keymaps/dencho_keymap/layout.json'
      - '.github/workflows/qmk_json_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repo (layout source)
        uses: actions/checkout@v4

      - name: Clone QMK Firmware
        run: git clone --depth 1 https://github.com/qmk/qmk_firmware.git

      - name: Copy your layout into QMK source
        run: |
          mkdir -p qmk_firmware/keyboards/mechboards/sofle/pro/keymaps/dencho_keymap
          cp keyboards/mechboards/sofle/pro/keymaps/dencho_keymap/layout.json \
             qmk_firmware/keyboards/mechboards/sofle/pro/keymaps/dencho_keymap/

      - name: Install AVR Toolchain (Minimal)
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-avr \
            avr-libc \
            binutils-avr \
            dfu-programmer \
            make \
            python3-pip

      - name: Install QMK CLI
        run: |
          python3 -m pip install qmk
          cd qmk_firmware
          qmk config user.keyboard=mechboards/sofle/pro
          qmk config user.keymap=dencho_keymap

      - name: Convert layout.json to keymap.c
        run: |
          cd qmk_firmware
          qmk json2c -kb mechboards/sofle/pro -km dencho_keymap \
            -o keyboards/mechboards/sofle/pro/keymaps/dencho_keymap/keymap.c \
            keyboards/mechboards/sofle/pro/keymaps/dencho_keymap/layout.json

      - name: Compile Sofle Firmware
        run: |
          cd qmk_firmware
          make mechboards/sofle/pro:dencho_keymap

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sofle-pro-firmware
          path: qmk_firmware/*.hex
