name: Build Sofle Pro Firmware from layout.json

on:
  push:
    paths:
      - 'keyboards/mechboards/sofle/pro/keymaps/dencho_keymap/layout.json'
      - '.github/workflows/qmk_json_build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install AVR Toolchain (Minimal)
        run: |
          sudo apt update
          sudo apt install -y \
            gcc-avr \
            avr-libc \
            binutils-avr \
            dfu-programmer \
            make \
            python3-pip

      - name: Install QMK CLI (No full setup)
        run: |
          python3 -m pip install qmk
          qmk config user.keyboard=mechboards/sofle/pro
          qmk config user.keymap=dencho_keymap

      - name: Convert layout.json to keymap.c
        run: |
          qmk json2c -kb mechboards/sofle/pro -km dencho_keymap \
            -o keyboards/mechboards/sofle/pro/keymaps/dencho_keymap/keymap.c \
            keyboards/mechboards/sofle/pro/keymaps/dencho_keymap/layout.json

      - name: Compile Sofle Firmware
        run: |
          make mechboards/sofle/pro:dencho_keymap

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sofle-pro-firmware
          path: "*.hex"
